language: node_js
node_js:
- '6.1'
before_install:
-  echo $PRODUSER
install:
- npm install
services: mongodb
before_script:
- export SSHPATH=ssh://$PRODUSER@$SERVERADDR/var/repo/site.git
- echo $SSHPATH
script:
- npm run build:server
- npm run build:client
after_success:
- ssh-add .travis/deploy_key.pem
- git remote add master $SSHPATH
- git push master
