language: node_js
node_js:
- '6.1'
before_install:
-  echo $PRODUSER
install:
- npm install
services: mongodb
script:
- npm run build:server
- npm run build:client
after_success:
- username: $PRODUSER
- ip: $SERVERADDR
- git remote add master ssh://username@ip/var/repo/site.git
- git push master
