language: node_js
node_js:
- '6.1'
before_install:
-  echo $PRODUSER
install:
- npm install
services: mongodb
script:
- npm run build:server
- npm run build:client
after_success:
- git remote add "ssh://" + $PRODUSER + "@" + $SERVERADDR +"/var/repo/site.git"
- git push master
