language: node_js
node_js:
- '6.1'
install:
- npm install
- git remote add "ssh://" + $PRODUSER + "@" + $SERVERADDR +"/var/repo/site.git"
services: mongodb
script:
- npm run build:server
- npm run build:client
after_success:
- git push master
